### ISSUE TITLE
Arguments are not used on http_conn_validator

### ISSUE THREAD

**Issue by elfranne** [voxpupuli/puppet-healthcheck#78]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.24.0
- Ruby: ruby 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [x86_64-linux]
- Distribution: Ubuntu
- Module version: 2.0.0

## How to reproduce (e.g Puppet code you use)
```puppet
http_conn_validator { 'influxdb-conn-validator_auth' :
    host      => 'localhost',
    port      => 8086,
    use_ssl   => false,
    test_url  => '/health',
    try_sleep => 5,
}
```

## Output log
```log
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection; sleeping 5 seconds before retry
Notice: Unable to connect to the server (http://localhost:8086/health): undefined method `fetch' for nil:NilClass
Notice: Failed to make an HTTP connection within timeout window of 60 seconds; giving up.
Notice: /Stage[main]/Influxdb/Http_conn_validator[influxdb-conn-validator_auth]/ensure: current_value 'absent', should be 'present' (noop) (corrective)
Debug: /Stage[main]/Influxdb/Http_conn_validator[influxdb-conn-validator_auth]: The container Class[Influxdb] will propagate my refresh event

```

## Any additional information you'd like to impart
Seems arguments are not to get passed on...
Works fine on 1.0.1
